<h1>NumPy</h1>

<p>NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. </p>


<p>At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:</p>


<ul>
<li>NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
</li>
<li>The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.</li>NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
<li> 
A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.
</li>

</ul>

<p>The points about sequence size and speed are particularly important in scientific computing. As a simple example, consider the case of multiplying each element in a 1-D sequence with the corresponding element in another sequence of the same length. If the data are stored in two Python lists, a and b, we could iterate over each element:</p>

<code>
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
</code>

<p>This produces the correct answer, but if a and b each contain millions of numbers, we will pay the price for the inefficiencies of looping in Python. We could accomplish the same task much more quickly in C by writing (for clarity we neglect variable declarations and initializations, memory allocation, etc.)</p>


<code>
for (i = 0; i < rows; i++): {
  c[i] = a[i]*b[i];
}
</code>

<p>This saves all the overhead involved in interpreting the Python code and manipulating Python objects, but at the expense of the benefits gained from coding in Python. Furthermore, the coding work required increases with the dimensionality of our data. In the case of a 2-D array, for example, the C code (abridged as before) expands to </p>


<code>
for (i = 0; i < rows; i++): {
  for (j = 0; j < columns; j++): {
    c[i][j] = a[i][j]*b[i][j];
  }
}
</code>

<p>NumPy gives us the best of both worlds: element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. In NumPy</p>


<code>
c = a * b
</code>

<p>does what the earlier examples do, at near-C speeds, but with the code simplicity we expect from something based on Python. Indeed, the NumPy idiom is even simpler! This last example illustrates two of NumPy’s features which are the basis of much of its power: vectorization and broadcasting.</p>

<p>Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:</p>


<ul>
<li>vectorized code is more concise and easier to read</li>
<li>fewer lines of code generally means fewer bugs</li>
<li>the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)</li>
<li>vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.
</li>
</ul>

<p>Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous. For detailed “rules” of broadcasting see numpy.doc.broadcasting.</p>

<p>NumPy fully supports an object-oriented approach, starting, once again, with ndarray. For example, ndarray is a class, possessing numerous methods and attributes. Many of its methods mirror functions in the outer-most NumPy namespace, giving the programmer complete freedom to code in whichever paradigm she prefers and/or which seems most appropriate to the task at hand.</p>

<h1>NumPy Data Types</h1>

<h2>Array types and conversions between types</h2>

<p>Numpy supports a much greater variety of numerical types than Python does. This section shows which are available, and how to modify an array’s data-type.</p>

<code>
Data type	Description
bool_	Boolean (True or False) stored as a byte
int_	Default integer type (same as C long; normally either int64 or int32)
intc	Identical to C int (normally int32 or int64)
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8	Byte (-128 to 127)
int16	Integer (-32768 to 32767)
int32	Integer (-2147483648 to 2147483647)
int64	Integer (-9223372036854775808 to 9223372036854775807)
uint8	Unsigned integer (0 to 255)
uint16	Unsigned integer (0 to 65535)
uint32	Unsigned integer (0 to 4294967295)
uint64	Unsigned integer (0 to 18446744073709551615)
float_	Shorthand for float64.
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_	Shorthand for complex128.
complex64	Complex number, represented by two 32-bit floats (real and imaginary components)
complex128	Complex number, represented by two 64-bit floats (real and imaginary components)
</code>

<p>Additionally to intc the platform dependent C integer types short, long, longlong and their unsigned versions are defined.
</p>
<p>Numpy numerical types are instances of dtype (data-type) objects, each having unique characteristics. Once you have imported NumPy using</p>


In [3]:
import numpy as np

<p>the dtypes are available as np.bool_, np.float32, etc.</p>

<p>Advanced types, not listed in the table above, are explored in section Structured arrays.</p>

<p>There are 5 basic numerical types representing booleans (bool), integers (int), unsigned integers (uint) floating point (float) and complex. Those with numbers in their name indicate the bitsize of the type (i.e. how many bits are needed to represent a single value in memory). Some types, such as int and intp, have differing bitsizes, dependent on the platforms (e.g. 32-bit vs. 64-bit machines). This should be taken into account when interfacing with low-level code (such as C or Fortran) where the raw memory is addressed.</p>


<p>
Data-types can be used as functions to convert python numbers to array scalars (see the array scalar section for an explanation), python sequences of numbers to arrays of that type, or as arguments to the dtype keyword that many numpy functions or methods accept. Some examples:</p>
    

In [5]:
import numpy as np   # import Numpy
x = np.float32(1.0)  # create a numpy 32 bit floating number variable an assign it a value of 1.0
print x
type(x)

1.0


numpy.float32

In [6]:
y = np.int_([1,2,4])  # create a numpy array of integers 32 or 64 bit, notice how it converts a python list into a numpy arra
print y
print y[0] # numpy arrays are indexed like lists 
type(y)    

[1 2 4]


numpy.ndarray

In [8]:
z = np.arange(3, dtype=np.uint8) # arange function creates a numpy array usinga a range function, 
                                 # first argument size, second data type.
print z
type(z)

[0 1 2]


numpy.ndarray

<p>Array types can also be referred to by character codes, mostly to retain backward compatibility with older packages such as Numeric. Some documentation may still refer to these, for example:</p>


In [11]:
a = np.array([1, 2, 3], dtype='f')  # uses old single character f to for float, also promotes integer range to float
print a
type(a)

[ 1.  2.  3.]


numpy.ndarray

<p>We recommend using dtype objects instead.</p>

<p>To convert the type of an array, use the .astype() method (preferred) or the type itself as a function. For example:<p>




In [17]:
print z               # z is an integer array
type (z)  
b = z.astype(float)   # astype method return an new numpy array which convert to specified type
print b
type (b)              # b is an array of converted floats from z

# alternatively you can use type itself as a function
c = np.float_(z)
print c
type (c) 

print z               # z is not changed.

[0 1 2]
[ 0.  1.  2.]
[ 0.  1.  2.]
[0 1 2]


<p>Note that, above, we use the Python float object as a dtype. NumPy knows that int refers to np.int_, bool means np.bool_, that float is np.float_ and complex is np.complex_. The other data-types do not have Python equivalents. </p>

<p>To determine the type of an array, look at the dtype attribute:</p>

In [21]:
print z.dtype
type(z)

uint8


numpy.ndarray

In [19]:
type(z)

numpy.ndarray

<p>dtype objects also contain information about the type, such as its bit-width and its byte-order. The data type can also be used indirectly to query properties of the type, such as whether it is an integer:</p>

In [30]:
d = np.dtype(int)
print d
isint = np.issubdtype(d,int)
print isint

ifloat = np.issubdtype(d,float)
print ifloat


int32
True
False


<h3>Array Scalars</h3>


<p>Numpy generally returns elements of arrays as array scalars (a scalar with an associated dtype). Array scalars differ from Python scalars, but for the most part they can be used interchangeably (the primary exception is for versions of Python older than v2.x, where integer array scalars cannot act as indices for lists and tuples). There are some exceptions, such as when code requires very specific attributes of a scalar or when it checks specifically whether a value is a Python scalar. Generally, problems are easily fixed by explicitly converting array scalars to Python scalars, using the corresponding Python type function (e.g., int, float, complex, str, unicode).</p>

<p>The primary advantage of using array scalars is that they preserve the array type (Python may not have a matching scalar type available, e.g. int16). Therefore, the use of array scalars ensures identical behaviour between arrays and scalars, irrespective of whether the value is inside an array or not. NumPy scalars also have many of the same methods arrays do.</p>
